
service: octoparse-postprocess-service       # Name of the service, which is used as a prefix to all function names. TODO: Update to your custom name.

provider:
  name: aws                   # Assuming this is for AWS Lambda.
  stage: dev                  # Name of the stage, typically either dev/staging/prod (or production), this is also added to all function names. TODO: Update to your custom name.
  profile: qa		      # Name of the pre-configured AWS profile that is founnd in ~/.aws/confidentials.  TODO: Update to your profile.
  region: us-east-1	      # Name of the region to deploy all functions to. TODO: Update to your custom region.
  runtime: python3.8          # AWS Lambda runtime

package:
  individually: true

functions:
  OctoparsePostProcess:
    handler: executor.main
    timeout: 900

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
